/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.SimpleDateFormat;
import java.time.Month;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ad
 */
public class frmNgaySinh extends javax.swing.JFrame {

    /**
     * Creates new form frmNgaySinh
     */
    public frmNgaySinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_ten = new javax.swing.JTextField();
        cbx_nam = new javax.swing.JCheckBox();
        cbx_nu = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        ngaysinh = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbx_nam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbx_nam.setText("Nam");

        cbx_nu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbx_nu.setText("Nữ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nhập ngày sinh");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Tra cứu cung hoàng đạo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nhập họ tên");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/goc.JPG"))); // NOI18N

        tb.setColumns(20);
        tb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tb.setRows(5);
        tb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(tb);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/goc3.JPG"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/goc2.JPG"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/goc1.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tracuu_1.JPG"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbx_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cbx_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(61, 61, 61)
                                                        .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(39, 39, 39)))))
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(86, 86, 86)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_nu)
                    .addComponent(cbx_nam))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6)
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        String ten = txt_ten.getText();
        Date ngaySinh = ngaysinh.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(ngaySinh);
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        int month = calendar.get(Calendar.MONTH) + 1;
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ngaySinhString = dateFormat.format(ngaySinh);
      
        if ((month == 3 && day >= 21) || (month == 4 && day <= 19)) {           
            System.out.println("Bạch Dương");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là tổng quan vắn tắt về Nam Bạch Dương -  "+ ten +"  \n" +
                                                                                                                "\n" +
                                "Ký hiệu: ♈\n" +
                                "Thời gian: 21/3 - 19/4 -> Bạn sinh ngày:  "+ngaySinhString+"  \n" +
                                "Nguyên tố: Lửa\n" +
                                "Hành tinh cai quản: Sao Hỏa\n" +
                                "Màu sắc: Đỏ, cam\n" +
                                "Đặc điểm chính:\n" +
                                "\n" +
                                "Mạnh mẽ, táo bạo, đầy nhiệt huyết và khao khát chinh phục\n" +
                                "Độc lập, tự do, không chịu bị ràng buộc\n" +
                                "Thẳng thắn, dứt khoát, không giấu giếm cảm xúc\n" +
                                "Hay nóng vội, ước muốn được hành động ngay lập tức\n" +
                                "Có tinh thần lãnh đạo, rất có sức ảnh hưởng với người khác\n" +
                                "Luôn muốn được khẳng định bản thân và có vị trí nổi bật\n" +
                                "Sức mạnh: Sáng tạo, can đảm, nhiệt huyết\n" +
                                "Yếu điểm: Nóng vội, bốc đồng, dễ kích động\n" +
                                "Sự nghiệp thích hợp: Lãnh đạo, kinh doanh, thể thao, nghệ thuật\n" +
                                "Tóm lại, Bạch Dương là cung hoàng đạo mang đầy năng lượng, nhiệt huyết và khao khát chinh phục thế giới";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là tổng quan vắn tắt về cung Nữ Bạch Dương  - "+ten+" \n" +
                                                                                    "\n" +
                                "Ký hiệu: ♈\n" +
                                "Thời gian: 21/3 - 19/4 -> Bạn sinh ngày:  "+ngaySinhString+" \n" +
                                "Nguyên tố: Lửa\n" +
                                "Hành tinh cai quản: Sao Hỏa\n" +
                                "Màu sắc: Đỏ, cam\n" +
                                "\n" +
                                "Đặc điểm chính:\n" +
                                "\n" +
                                "Mạnh mẽ, độc lập, không chịu bị ràng buộc\n" +
                                "Tự tin, can đảm, không ngại thử thách mới\n" +
                                "Hoạt bát, nhiệt tình, thích được công nhận\n" +
                                "Nóng nảy, thẳng thắn, không giấu giếm cảm xúc\n" +
                                "Thích khám phá, khao khát chinh phục thế giới\n" +
                                "Có tinh thần lãnh đạo, ảnh hưởng mạnh đến người khác\n" +
                                "Sức mạnh: Sáng tạo, nhiệt huyết, dám nghĩ dám làm\n" +
                                "Yếu điểm: Bốc đồng, nóng vội, dễ kích động\n" +
                                "Sự nghiệp thích hợp: Kinh doanh, thể thao, nghệ thuật, khoa học\n" +
                                "\n" +
                                "Tóm lại, Nữ Bạch Dương là một cung hoàng đạo mạnh mẽ, độc lập và luôn khao khát chinh phục thế giới. Họ là những người đầy nhiệt huyết và dám nghĩ dám làm.";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        
        }      
        else if ((month == 4 && day >= 20) || (month == 5 && day <= 20)){
            System.out.println("Kim Ngưu");
            
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là tổng quan vắn tắt về Nam Kim Ngưu - "+ten+"\n" +
                                                                            "\n" +
                                "Nam Kim Ngưu -> Bạn sinh ngày:  "+ngaySinhString+"\n" +
                                "Tổng quan:\n" +
                                "\n" +
                                "Nam Kim Ngưu là một trong 12 cung hoàng đạo trong chiêm tinh học.\n" +
                                "Những người thuộc cung này thường có tính cách ổn định, thực tế và kiên nhẫn.\n" +
                                "Họ trân trọng sự an toàn, thoải mái và ổn định về tài chính, vật chất.\n" +
                                "Đặc điểm tính cách:\n" +
                                "\n" +
                                "Ổn định, thực tế và kiên nhẫn\n" +
                                "Trân trọng sự an toàn, thoải mái và ổn định về tài chính, vật chất\n" +
                                "Có xu hướng thích tích lũy tài sản và tiết kiệm\n" +
                                "Không thích những thay đổi đột ngột hoặc rủi ro\n" +
                                "Có thể hơi chậm chạp và thiếu linh hoạt\n" +
                                "Sở thích và công việc:\n" +
                                "\n" +
                                 "Thích các hoạt động liên quan đến cảm giác như nghệ thuật, nấu ăn, làm vườn\n" +
                                "Thích các công việc ổn định, có thu nhập cao và các lợi ích tốt\n" +
                                "Phù hợp với các ngành như tài chính, ngân hàng, bất động sản, nông nghiệp\n" +
                                "Nhận xét:\n" +
                                "\n" +
                                "Là một trong những cung hoàng đạo ổn định và đáng tin cậy nhất\n" +
                                "Cần cù, chăm chỉ và trung thành trong các mối quan hệ\n" +
                                "Có thể khó thích nghi với những thay đổi và rủi ro\n" +
                                "Tóm lại, Nam Kim Ngưu là một cung hoàng đạo thực tế, ổn định và trân trọng sự an toàn về vật chất. Họ có xu hướng tích lũy tài sản và không ưa thích những thay đổi đột ngột";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là tổng quan vắn tắt về Nữ Kim Ngưu - "+ten+"\n" +
                                                                            "\n" +
                                "Nữ Kim Ngưu -> Bạn sinh ngày:  "+ngaySinhString+"\n" +
                                "Tổng quan:\n" +
                                                                            "\n" +
                                "Nữ Kim Ngưu là một trong 12 cung hoàng đạo trong chiêm tinh học.\n" +
                                "Những người thuộc cung này thường có tính cách ổn định, thực tế và trân trọng sự thoải mái, an toàn.\n" +
                                "Họ chú trọng vào việc xây dựng cuộc sống vật chất và tài chính an toàn.\n" +
                                "Đặc điểm tính cách:\n" +
                                                                            "\n" +
                                "Ổn định, thực tế và trân trọng sự thoải mái, an toàn\n" +
                                "Có xu hướng tích lũy tài sản và tiết kiệm\n" +
                                "Thích sự tiện nghi, xa hoa và những thứ đẹp đẽ\n" +
                                "Không thích những thay đổi đột ngột hoặc rủi ro\n" +
                                "Có thể hơi chậm chạp và thiếu linh hoạt\n" +
                                "Sở thích và công việc:\n" +
                                                                                "\n" +
                                "Thích các hoạt động liên quan đến cảm giác như nghệ thuật, nấu ăn, làm vườn\n" +
                                "Thích các công việc ổn định, có thu nhập cao và các lợi ích tốt\n" +
                                "Phù hợp với các ngành như tài chính, ngân hàng, bất động sản, nông nghiệp\n" +
                                "Nhận xét:\n" +
                                                                                    "\n" +
                                "Là một trong những cung hoàng đạo ổn định, đáng tin cậy và có cái nhìn thực tế nhất\n" +
                                "Cần cù, chăm chỉ và trung thành trong các mối quan hệ\n" +
                                "Có thể khó thích nghi với những thay đổi và rủi ro\n" +
                                "Tóm lại, Nữ Kim Ngưu là một cung hoàng đạo thực tế, ổn định và trân trọng sự thoải mái, an toàn về vật chất. Họ có xu hướng tích lũy tài sản và không ưa thích những thay đổi đột ngột";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 5 && day >= 21) || (month == 6 && day <= 20)){
            System.out.println("Song tử");
           if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Song Tử - "+ten+"\n" +
                                "\n" + 
                                "Nam Song Tử là một trong 12 chòm sao của Hoàng Đạo. Người thuộc chòm sao này thường sinh ra vào khoảng từ 21/5 đến 21/6 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+" \n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Song Tử:\n" +
                                "\n" +
                                "Thông minh, nhanh nhẹn, đa tài và hiếu học\n" +
                                "Tò mò, thích khám phá và học hỏi điều mới\n" +
                                "Giao tiếp tốt, linh hoạt, thích thay đổi và đa dạng\n" +
                                "Hay thay đổi ý kiến, khó đưa ra quyết định dứt khoát\n" +
                                "Bề ngoài thoạt nhìn lạnh lùng nhưng bên trong thực sự rất mềm mại\n" +
                                "Sức mạnh của họ nằm ở khả năng giao tiếp và suy nghĩ linh hoạt. Họ hợp nhất với những người cùng tính cách năng động và sáng tạo như Bạch Dương và Thiên Bình. Nhược điểm là thường khó có được sự ổn định và kỷ luật trong cuộc sống.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Song Tử - "+ten+"\n" +
                                "\n" +
                                "Nữ Song Tử là người thuộc chòm sao Song Tử, với khoảng thời gian sinh vào khoảng từ 21/5 đến 21/6 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Song Tử:\n" +
                                "\n" +
                                "Thông minh, nhanh nhẹn và đa tài\n" +
                                "Hiếu kỳ, thích tìm tòi và học hỏi điều mới\n" +
                                "Giao tiếp tốt, linh hoạt và có khiếu hài hước\n" +
                                "Có nhiều sở thích và dễ thay đổi ý kiến\n" +
                                "Bề ngoài có vẻ lạnh lùng nhưng bên trong rất mềm mại\n" +
                                "Sức mạnh của họ nằm ở khả năng giao tiếp tuyệt vời, tư duy linh hoạt và sáng tạo. Họ hợp với những người có tính cách năng động như Bạch Dương và Thiên Bình. Nhược điểm là họ thường khó đưa ra quyết định dứt khoát và duy trì sự ổn định trong cuộc sống";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 6 && day >= 21) || (month == 7 && day <= 22)){
            System.out.println("Cự giải");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Cự Giải - "+ten+"\n" +
                                "\n" +
                                "Nam Cự Giải là người thuộc chòm sao Cự Giải, với khoảng thời gian sinh vào khoảng từ 22/6 đến 22/7 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Cự Giải:\n" +
                                "\n" +
                                "Tính cách ấm áp, chu đáo và rất sentimental\n" +
                                "Rất trung thành, bảo vệ gia đình và bạn bè\n" +
                                "Thường trầm lặng, nhạy cảm và dễ bị tổn thương\n" +
                                "Thích sự an toàn, ổn định và dễ có thói quen\n" +
                                "Có khả năng cảm nhận và đồng cảm với người khác\n" +
                                "Sức mạnh của họ nằm ở lòng trung thành, sự chu đáo và khả năng cảm thông với người khác. Họ tương đối hợp với những người Bò Cạp và Thiên Bình. Nhược điểm là họ thường có xu hướng cảm xúc cao và dễ trở nên bảo thủ, cứng nhắc.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Cự Giải - "+ten+"\n" +
                                "\n" +
                                "Nữ Cự Giải là người thuộc chòm sao Cự Giải, với khoảng thời gian sinh vào khoảng từ 22/6 đến 22/7 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Cự Giải:\n" +
                                "\n" +
                                "Tính cách ấm áp, chu đáo và rất sentimental\n" +
                                "Rất trung thành, bảo vệ gia đình và bạn bè\n" +
                                "Thường trầm lặng, nhạy cảm và dễ bị tổn thương\n" +
                                "Thích sự an toàn, ổn định và dễ có thói quen\n" +
                                "Có khả năng cảm nhận và đồng cảm với người khác\n" +
                                "Sức mạnh của họ nằm ở lòng trung thành, sự chu đáo và khả năng cảm thông với người khác. Họ tương đối hợp với những người Bò Cạp và Thiên Bình. Nhược điểm là họ thường có xu hướng cảm xúc cao và dễ trở nên bảo thủ, cứng nhắc.";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 7 && day >= 23) || (month == 8 && day <= 22)){
            System.out.println("Sư tử");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Sư Tử - "+ten+"\n" +
                                "\n" +
                                "Nam Sư Tử là người thuộc chòm sao Sư Tử, với khoảng thời gian sinh vào khoảng từ 23/7 đến 22/8 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+" .\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Sư Tử:\n" +
                                "\n" +
                                "Tự tin, mạnh mẽ và có tính lãnh đạo\n" +
                                "Rất sáng tạo, có khiếu nghệ thuật và thích được công nhận\n" +
                                "Thường có sức hút và phong cách quyến rũ\n" +
                                "Nhiệt tình, đầy nhiệt huyết nhưng cũng hơi ích kỷ\n" +
                                "Thích được ngưỡng mộ và được mọi người chú ý\n" +
                                "Sức mạnh của họ nằm ở sự tự tin, sáng tạo và khả năng lãnh đạo. Họ hợp với những người Bạch Dương và Nhân Mã. Nhược điểm là họ có thể hơi độc đoán, tham vọng và nóng tính.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Sư Tử - "+ten+"\n" +
                            "\n" +
                            "Nữ Sư Tử là người thuộc chòm sao Sư Tử, với khoảng thời gian sinh vào khoảng từ 23/7 đến 22/8 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                            "\n" +
                            "Những đặc điểm nổi bật của người Nữ Sư Tử:\n" +
                            "\n" +
                            "Tự tin, mạnh mẽ và có tính lãnh đạo\n" +
                            "Rất sáng tạo, có khiếu nghệ thuật và thích được công nhận\n" +
                            "Thường có sức hút và phong cách quyến rũ\n" +
                            "Nhiệt tình, đầy nhiệt huyết nhưng cũng hơi ích kỷ\n" +
                            "Thích được ngưỡng mộ và được mọi người chú ý\n" +
                            "Sức mạnh của họ nằm ở sự tự tin, sáng tạo và khả năng lãnh đạo. Họ hợp với những người Bạch Dương và Nhân Mã. Nhược điểm là họ có thể hơi độc đoán, tham vọng và nóng tính.";
            tb.setText(longText);  
            
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 8 && day >= 23) || (month == 9 && day <= 22)){
            System.out.println("Xử nữ");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Xử Nữ - "+ten+"\n" +
                                "\n" +
                                "Nam Xử Nữ là người thuộc chòm sao Xử Nữ, với khoảng thời gian sinh vào khoảng từ 23/8 đến 22/9 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Xử Nữ:\n" +
                                "\n" +
                                "Có tính cách cẩn thận, logic và phân tích kỹ lưỡng\n" +
                                "Rất tỉ mỉ, cẩn trọng và luôn muốn hoàn thiện mọi việc\n" +
                                "Thực tế, thông minh và có khả năng giải quyết vấn đề tốt\n" +
                                "Dễ bị stress, lo lắng và khó chấp nhận sự không hoàn hảo\n" +
                                "Trung thành, chu đáo và hay phán xét người khác\n" +
                                "Sức mạnh của họ nằm ở sự tỉ mỉ, logic và khả năng giải quyết vấn đề. Họ hợp với những người Bò Cạp và Song Ngư. Nhược điểm là họ có thể quá cẩn thận, khắt khe và khó thoải mái.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Xử Nữ - "+ten+"\n" +
                                "\n" +
                                "Nữ Xử Nữ là người thuộc chòm sao Xử Nữ, với khoảng thời gian sinh vào khoảng từ 23/8 đến 22/9 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+"\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Xử Nữ:\n" +
                                "\n" +
                                "Có tính cách cẩn thận, logic và phân tích kỹ lưỡng\n" +
                                "Rất tỉ mỉ, cẩn trọng và luôn muốn hoàn thiện mọi việc\n" +
                                "Thực tế, thông minh và có khả năng giải quyết vấn đề tốt\n" +
                                "Dễ bị stress, lo lắng và khó chấp nhận sự không hoàn hảo\n" +
                                "Trung thành, chu đáo và hay phán xét người khác\n" +
                                "Sức mạnh của họ nằm ở sự tỉ mỉ, logic và khả năng giải quyết vấn đề. Họ hợp với những người Bò Cạp và Song Ngư. Nhược điểm là họ có thể quá cẩn thận, khắt khe và khó thoải mái.";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 9 && day >= 23) || (month == 10 && day <= 22)){
            System.out.println("Thiên bình");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Thiên Bình - "+ten+"\n" +
                                "\n" +
                                "Nam Thiên Bình là người thuộc chòm sao Thiên Bình, với khoảng thời gian sinh vào khoảng từ 23/9 đến 22/10 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Thiên Bình:\n" +
                                "\n" +
                                "Rất cân bằng, công bằng và tìm kiếm sự hài hòa\n" +
                                "Có phong cách lịch sự, dễ gần và thích giao tiếp\n" +
                                "Thích sự ổn định, tránh xung đột và phê phán\n" +
                                "Dễ bị ảnh hưởng bởi ý kiến của người khác\n" +
                                "Có khiếu thẩm mỹ và đánh giá cao nghệ thuật\n" +
                                "Sức mạnh của họ nằm ở sự cân bằng, công bằng và giao tiếp. Họ hợp với những người Song Tử và Bảo Bình. Nhược điểm là họ có thể quá nhượng bộ, khó đưa ra quyết định và dễ phụ thuộc vào người khác.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Thiên Bình - "+ten+"\n" +
                                "\n" +
                                "Nữ Thiên Bình là người thuộc chòm sao Thiên Bình, với khoảng thời gian sinh vào khoảng từ 23/9 đến 22/10 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Thiên Bình:\n" +
                                "\n" +
                                "Rất cân bằng, công bằng và tìm kiếm sự hài hòa\n" +
                                "Có phong cách lịch sự, dễ gần và thích giao tiếp\n" +
                                "Thích sự ổn định, tránh xung đột và phê phán\n" +
                                "Dễ bị ảnh hưởng bởi ý kiến của người khác\n" +
                                "Có khiếu thẩm mỹ và đánh giá cao nghệ thuật\n" +
                                "Sức mạnh của họ nằm ở sự cân bằng, công bằng và giao tiếp. Họ hợp với những người Song Tử và Bảo Bình. Nhược điểm là họ có thể quá nhượng bộ, khó đưa ra quyết định và dễ phụ thuộc vào người khác";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 10 && day >= 23) || (month == 11 && day <= 21)){
            System.out.println("Bọ cạp");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Bọ Cạp - "+ten+"\n" +
                                "\n" +
                                "Nam Bọ Cạp là người thuộc chòm sao Bọ Cạp, với khoảng thời gian sinh vào khoảng từ 23/10 đến 21/11 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Bọ Cạp:\n" +
                                "\n" +
                                "Có tính cách mạnh mẽ, kiên định và có sự tập trung cao\n" +
                                "Rất đam mê, sâu sắc và quan tâm đến những chi tiết nhỏ\n" +
                                "Không ngại thách thức, tính toán kỹ lưỡng và ham tìm hiểu\n" +
                                "Khó tin tưởng người khác và có thể rất bí ẩn, ghen tuông\n" +
                                "Quyết đoán, không thích sự lỏng lẻo và làm việc chăm chỉ\n" +
                                "Sức mạnh của họ nằm ở sự tập trung, quyết đoán và khả năng đi sâu vào chi tiết. Họ hợp với những người Xử Nữ và Cự Giải. Nhược điểm là họ có thể quá nghi ngờ, kiểm soát và khó thay đổi.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Bọ Cạp - "+ten+"\n" +
                                "\n" +
                                "Nữ Bọ Cạp là người thuộc chòm sao Bọ Cạp, với khoảng thời gian sinh vào khoảng từ 23/10 đến 21/11 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Bọ Cạp:\n" +
                                "\n" +
                                "Có tính cách mạnh mẽ, kiên định và có sự tập trung cao\n" +
                                "Rất đam mê, sâu sắc và quan tâm đến những chi tiết nhỏ\n" +
                                "Không ngại thách thức, tính toán kỹ lưỡng và ham tìm hiểu\n" +
                                "Khó tin tưởng người khác và có thể rất bí ẩn, ghen tuông\n" +
                                "Quyết đoán, không thích sự lỏng lẻo và làm việc chăm chỉ\n" +
                                "Sức mạnh của họ nằm ở sự tập trung, quyết đoán và khả năng đi sâu vào chi tiết. Họ hợp với những người Xử Nữ và Cự Giải. Nhược điểm là họ có thể quá nghi ngờ, kiểm soát và khó thay đổi";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 11 && day >= 22) || (month == 12 && day <= 21)){
            System.out.println("Nhân mã");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Nhân Mã - "+ten+"\n" +
                                "\n" +
                                "Nam Nhân Mã là người thuộc chòm sao Nhân Mã, với khoảng thời gian sinh vào khoảng từ 22/11 đến 21/12 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Nhân Mã:\n" +
                                "\n" +
                                "Có tính cách phóng khoáng, lạc quan và ham hiểu biết\n" +
                                "Rất cởi mở, thích phiêu lưu và luôn tìm kiếm cái mới\n" +
                                "Có năng lượng dồi dào, nhiệt huyết và không ngại thử thách\n" +
                                "Có thể bị xao lãng nhanh chóng và không kiên nhẫn\n" +
                                "Tự do và không thích bị ràng buộc, thích đương đầu với rủi ro\n" +
                                "Sức mạnh của họ nằm ở sự phóng khoáng, nhiệt tình và khao khát khám phá. Họ hợp với những người Bạch Dương và Sư Tử. Nhược điểm là họ có thể lỏng lẻo, thiếu tập trung và không thích sự ràng buộc.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Nhân Mã - "+ten+"\n" +
                                "\n" +
                                "Nữ Nhân Mã là người thuộc chòm sao Nhân Mã, với khoảng thời gian sinh vào khoảng từ 22/11 đến 21/12 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Nhân Mã:\n" +
                                "\n" +
                                "Có tính cách phóng khoáng, lạc quan và ham hiểu biết\n" +
                                "Rất cởi mở, thích phiêu lưu và luôn tìm kiếm cái mới\n" +
                                "Có năng lượng dồi dào, nhiệt huyết và không ngại thử thách\n" +
                                "Có thể bị xao lãng nhanh chóng và không kiên nhẫn\n" +
                                "Tự do và không thích bị ràng buộc, thích đương đầu với rủi ro\n" +
                                "Sức mạnh của họ nằm ở sự phóng khoáng, nhiệt tình và khao khát khám phá. Họ hợp với những người Bạch Dương và Sư Tử. Nhược điểm là họ có thể lỏng lẻo, thiếu tập trung và không thích sự ràng buộc";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 12 && day >= 22) || (month == 1 && day <= 19)){
            System.out.println("Ma kết");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Ma Kết - "+ten+"\n" +
                                "\n" +
                                "Nam Ma Kết là người thuộc chòm sao Ma Kết, với khoảng thời gian sinh vào khoảng từ 22/12 đến 19/1 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Ma Kết:\n" +
                                "\n" +
                                "Có tính cách thực tế, kiên định và cẩn thận\n" +
                                "Rất có trách nhiệm, tỉ mỉ và đáng tin cậy\n" +
                                "Thích sự ổn định, an toàn và sự tổ chức\n" +
                                "Khó thay đổi, chuộng truyền thống và không thích rủi ro\n" +
                                "Tập trung, kiên nhẫn và không thích sự lãng phí\n" +
                                "Sức mạnh của họ nằm ở sự kiên định, trách nhiệm và khả năng tập trung. Họ hợp với những người Xử Nữ và Song Ngư. Nhược điểm là họ có thể quá bảo thủ, thiếu sáng tạo và không linh hoạt.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Ma Kết - "+ten+"\n" +
                                "\n" +
                                "Nữ Ma Kết là người thuộc chòm sao Ma Kết, với khoảng thời gian sinh vào khoảng từ 22/12 đến 19/1 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Ma Kết:\n" +
                                "\n" +
                                "Có tính cách thực tế, kiên định và cẩn thận\n" +
                                "Rất có trách nhiệm, tỉ mỉ và đáng tin cậy\n" +
                                "Thích sự ổn định, an toàn và sự tổ chức\n" +
                                "Khó thay đổi, chuộng truyền thống và không thích rủi ro\n" +
                                "Tập trung, kiên nhẫn và không thích sự lãng phí\n" +
                                "Sức mạnh của họ nằm ở sự kiên định, trách nhiệm và khả năng tập trung. Họ hợp với những người Xử Nữ và Song Ngư. Nhược điểm là họ có thể quá bảo thủ, thiếu sáng tạo và không linh hoạt";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 1 && day >= 20) || (month == 2 && day <= 18)){
            System.out.println("Bảo bình");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Bảo Bình - "+ten+"\n" +
                                "\n" +
                                "Nam Bảo Bình là người thuộc chòm sao Bảo Bình, với khoảng thời gian sinh vào khoảng từ 20/1 đến 18/2 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Bảo Bình:\n" +
                                "\n" +
                                "Có tính cách độc lập, cá tính và có tinh thần nhân văn\n" +
                                "Rất sáng tạo, luôn muốn khám phá và tìm tòi cái mới\n" +
                                "Thích sự tự do, ghét bị ràng buộc và không thích quy tắc\n" +
                                "Có tinh thần phản biện cao, phóng khoáng và không gia trưởng\n" +
                                "Coi trọng bạn bè, gia đình và có tính nhân ái, tốt bụng\n" +
                                "Sức mạnh của họ nằm ở sự sáng tạo, độc lập và tinh thần nhân văn. Họ hợp với những người Song Ngư và Bạch Dương. Nhược điểm là họ có thể hơi cực đoan, không chịu ràng buộc và thiếu kiên nhẫn.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Bảo Bình - "+ten+"\n" +
                                "\n" +
                                "Nữ Bảo Bình là người thuộc chòm sao Bảo Bình, với khoảng thời gian sinh vào khoảng từ 20/1 đến 18/2 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Bảo Bình:\n" +
                                "\n" +
                                "Có tính cách độc lập, cá tính và có tinh thần nhân văn\n" +
                                "Rất sáng tạo, luôn muốn khám phá và tìm tòi cái mới\n" +
                                "Thích sự tự do, ghét bị ràng buộc và không thích quy tắc\n" +
                                "Có tinh thần phản biện cao, phóng khoáng và không gia trưởng\n" +
                                "Coi trọng bạn bè, gia đình và có tính nhân ái, tốt bụng\n" +
                                "Sức mạnh của họ nằm ở sự sáng tạo, độc lập và tinh thần nhân văn. Họ hợp với những người Song Ngư và Bạch Dương. Nhược điểm là họ có thể hơi cực đoan, không chịu ràng buộc và thiếu kiên nhẫn";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else if ((month == 2 && day >= 19) || (month == 3 && day <= 20)){
            System.out.println("Song Ngư");
            if(cbx_nam.isSelected() && !cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nam Song Ngư - "+ten+"\n" +
                                "\n" +
                                "Nam Song Ngư là người thuộc chòm sao Song Ngư, với khoảng thời gian sinh vào khoảng từ 19/2 đến 20/3 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nam Song Ngư:\n" +
                                "\n" +
                                "Có tính cách linh hoạt, trực giác và có sức tưởng tượng phong phú\n" +
                                "Rất nhạy cảm, thông cảm và có khả năng đồng cảm cao\n" +
                                "Thích sự huyền bí, tránh hiện thực và hay thay đổi tâm trạng\n" +
                                "Có khát vọng khám phá và muốn được tự do, thoải mái\n" +
                                "Coi trọng các mối quan hệ, tình cảm và có ảnh hưởng mạnh từ môi trường xung quanh\n" +
                                "Sức mạnh của họ nằm ở sự trực giác, sáng tạo và khả năng đồng cảm. Họ hợp với những người Ma Kết và Xử Nữ. Nhược điểm là họ có thể thiếu tập trung, không thực tế và dễ bị ảnh hưởng.";
            tb.setText(longText);           
        }   else if(!cbx_nam.isSelected() && cbx_nu.isSelected()){
            String longText = "Dưới đây là một bản giới thiệu ngắn gọn về Nữ Song Ngư - "+ten+"\n" +
                                "\n" +
                                "Nữ Song Ngư là người thuộc chòm sao Song Ngư, với khoảng thời gian sinh vào khoảng từ 19/2 đến 20/3 hàng năm -> Bạn sinh ngày:  "+ngaySinhString+".\n" +
                                "\n" +
                                "Những đặc điểm nổi bật của người Nữ Song Ngư:\n" +
                                "\n" +
                                "Có tính cách linh hoạt, trực giác và có sức tưởng tượng phong phú\n" +
                                "Rất nhạy cảm, thông cảm và có khả năng đồng cảm cao\n" +
                                "Thích sự huyền bí, tránh hiện thực và hay thay đổi tâm trạng\n" +
                                "Có khát vọng khám phá và muốn được tự do, thoải mái\n" +
                                "Coi trọng các mối quan hệ, tình cảm và có ảnh hưởng mạnh từ môi trường xung quanh\n" +
                                "Sức mạnh của họ nằm ở sự trực giác, sáng tạo và khả năng đồng cảm. Họ hợp với những người Ma Kết và Xử Nữ. Nhược điểm là họ có thể thiếu tập trung, không thực tế và dễ bị ảnh hưởng";
            tb.setText(longText);           
        }
            else if((!cbx_nam.isSelected() && !cbx_nu.isSelected()) || (cbx_nam.isSelected() && cbx_nu.isSelected()) ){
                int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }   
            }
        }
        else{
             int response = JOptionPane.showConfirmDialog(this, "Bạn có muốn nhập lại không?", "Bạn đã nhập sai?", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.NO_OPTION) {
                    // Đóng ứng dụng
                    this.dispose();
                } else {
                    // Người dùng chọn "Không", không làm gì cả
                    System.out.println("Thoát ứng dụng đã bị hủy.");
                }     
        }   
        
        
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNgaySinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbx_nam;
    private javax.swing.JCheckBox cbx_nu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private de.wannawork.jcalendar.JCalendarComboBox ngaysinh;
    private javax.swing.JTextArea tb;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
